secretGenerator:
- name: wordpress-secret
  literals:
  - password=D#9v@Gp6Rt$zQ3jW
  - dbname=wordpress
  - dbuser=ppm-wordpress
  - dbhost=10.20.50.95
resources:
  - wordpress/wordpress-storage-class.yaml
  - wordpress/pv-wordpress.yaml
  - wordpress/pvc-wordpress.yaml
  - wordpress/wordpress-deployment.yaml
  - wordpress/wordpress-ingress.yaml