# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: wordpress-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: wordpress-local-storage
#   hostPath:
#     path: /tmp/wp/data

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.20.50.95
    path: /media/wp-content