apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  # type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: pholophus/my-wordpress-image:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: dbhost
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: password
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: dbuser
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: dbname
        ports:
        - containerPort: 80
          name: wordpress
        # volumeMounts:
        # - name: wordpress-persistent-storage  # Update to match volume name
        #   mountPath: /var/www/html
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html/wp-content
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-pvc


      # imagePullSecrets:
      #   - name: regcred
      # volumes:
      # - name: wordpress-persistent-storage  # Keep volume name consistent
      #   persistentVolumeClaim:
      #     claimName: wp-pv-claim