apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
data:
  wp-config.php: |
    <?php
    define( 'DB_NAME', 'your_database_name_here' );
    define( 'DB_USER', 'your_database_user_here' );
    define( 'DB_PASSWORD', 'your_database_password_here' );
    define( 'DB_HOST', 'your_database_host_here' );
