apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: mysql-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi